"""add_case_workflow_state

Revision ID: 3309ce67a1ab
Revises: 70d1356ca59c
Create Date: 2026-07-15 00:45:03.775483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3309ce67a1ab'
down_revision: Union[str, None] = '70d1356ca59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_workflow_state',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=False),
    sa.Column('blocker_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_action_type', sa.String(length=120), nullable=True),
    sa.Column('next_action_label', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_workflow_state')
    # ### end Alembic commands ###
