"""update schema sync

Revision ID: 4489fab61be8
Revises: c3d4e5f6a7b8
Create Date: 2026-08-18 18:58:53.189500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4489fab61be8'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_breaches_scan_id', table_name='data_breaches')
    op.drop_index('ix_data_breaches_severity', table_name='data_breaches')
    op.add_column('evidence_files', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.add_column('evidence_files', sa.Column('transcript', sa.String(length=5000), nullable=True))
    op.add_column('evidence_files', sa.Column('translation', sa.String(length=5000), nullable=True))
    op.add_column('investigation_paths', sa.Column('parent_path_id', sa.Uuid(), nullable=True))
    op.add_column('investigation_paths', sa.Column('revision_number', sa.Integer(), nullable=False))
    op.add_column('investigation_paths', sa.Column('trigger_type', sa.String(length=64), nullable=False))
    op.add_column('investigation_paths', sa.Column('change_reason', sa.Text(), nullable=True))
    op.add_column('investigation_paths', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'investigation_paths', 'investigation_paths', ['parent_path_id'], ['id'])
    op.drop_index('ix_osint_scans_case_status', table_name='osint_scans')
    op.drop_index('ix_osint_scans_entity_id', table_name='osint_scans')
    op.drop_index('ix_osint_snapshots_case_id', table_name='osint_snapshots')
    op.drop_index('ix_osint_snapshots_entity_id', table_name='osint_snapshots')
    op.drop_index('ix_osint_snapshots_scan_id', table_name='osint_snapshots')
    op.drop_index('ix_social_profiles_platform', table_name='social_profiles')
    op.drop_index('ix_social_profiles_scan_id', table_name='social_profiles')
    op.alter_column('timeline_events', 'event_type',
               existing_type=sa.VARCHAR(length=40),
               comment='One of: complaint_filed, entity_extracted, path_generated, step_completed, request_dispatched, response_received, cctv_frame, officer_note',
               existing_nullable=False)
    op.drop_index('ix_timeline_events_case_id', table_name='timeline_events')
    op.drop_index('ix_timeline_events_occurred_at', table_name='timeline_events')
    op.drop_constraint('timeline_events_case_id_fkey', 'timeline_events', type_='foreignkey')
    op.drop_constraint('timeline_events_evidence_file_id_fkey', 'timeline_events', type_='foreignkey')
    op.create_foreign_key(None, 'timeline_events', 'evidence_files', ['evidence_file_id'], ['id'])
    op.create_foreign_key(None, 'timeline_events', 'cases', ['case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeline_events', type_='foreignkey')
    op.drop_constraint(None, 'timeline_events', type_='foreignkey')
    op.create_foreign_key('timeline_events_evidence_file_id_fkey', 'timeline_events', 'evidence_files', ['evidence_file_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('timeline_events_case_id_fkey', 'timeline_events', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_timeline_events_occurred_at', 'timeline_events', ['occurred_at'], unique=False)
    op.create_index('ix_timeline_events_case_id', 'timeline_events', ['case_id'], unique=False)
    op.alter_column('timeline_events', 'event_type',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='One of: complaint_filed, entity_extracted, path_generated, step_completed, request_dispatched, response_received, cctv_frame, officer_note',
               existing_nullable=False)
    op.create_index('ix_social_profiles_scan_id', 'social_profiles', ['scan_id'], unique=False)
    op.create_index('ix_social_profiles_platform', 'social_profiles', ['platform'], unique=False)
    op.create_index('ix_osint_snapshots_scan_id', 'osint_snapshots', ['scan_id'], unique=False)
    op.create_index('ix_osint_snapshots_entity_id', 'osint_snapshots', ['entity_id'], unique=False)
    op.create_index('ix_osint_snapshots_case_id', 'osint_snapshots', ['case_id'], unique=False)
    op.create_index('ix_osint_scans_entity_id', 'osint_scans', ['entity_id'], unique=False)
    op.create_index('ix_osint_scans_case_status', 'osint_scans', ['case_id', 'status'], unique=False)
    op.drop_constraint(None, 'investigation_paths', type_='foreignkey')
    op.drop_column('investigation_paths', 'is_active')
    op.drop_column('investigation_paths', 'change_reason')
    op.drop_column('investigation_paths', 'trigger_type')
    op.drop_column('investigation_paths', 'revision_number')
    op.drop_column('investigation_paths', 'parent_path_id')
    op.drop_column('evidence_files', 'translation')
    op.drop_column('evidence_files', 'transcript')
    op.drop_column('evidence_files', 'file_type')
    op.create_index('ix_data_breaches_severity', 'data_breaches', ['severity'], unique=False)
    op.create_index('ix_data_breaches_scan_id', 'data_breaches', ['scan_id'], unique=False)
    # ### end Alembic commands ###
