"""add_case_section_status

Revision ID: 70d1356ca59c
Revises: 0001_initial_schema
Create Date: 2026-07-07 01:26:05.485558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d1356ca59c'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_sections', sa.Column('status', sa.String(length=32), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_sections', 'status')
    # ### end Alembic commands ###
