"""
Database Models — SQLAlchemy ORM Definitions
=============================================
Defines all database tables for the video incident analyzer:

    - VideoCase: Represents an uploaded video and its analysis state
    - ChronologicalLog: Individual timeline entries from the AI analysis
    - LedgerEntry: Tamper-evident hash-chained audit log entries

Design Decisions:
    - UUIDs for VideoCase IDs (server-generated via gen_random_uuid())
    - Explicit sequence_order on ChronologicalLog for deterministic timeline rendering
    - CASCADE delete from VideoCase → ChronologicalLog (no orphaned rows)
    - Append-only LedgerEntry table enforced by database triggers (Stage 1.2)
    - JSONB for ledger payload_snapshot for flexible event data storage
    - PostgreSQL ARRAY type for entities_detected to avoid a join table

Indexes:
    - VideoCase.status (filter by processing state)
    - ChronologicalLog.(case_id, sequence_order) composite (ordered timeline queries)
    - LedgerEntry.case_id (chain verification lookups)
"""

import enum
from datetime import datetime, timezone
from typing import List, Optional
from uuid import uuid4

from sqlalchemy import (
    BigInteger,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


# ── Base Class ────────────────────────────────────────────────────────────────
class Base(DeclarativeBase):
    """Declarative base for all ORM models."""
    pass


# ── Enumerations ──────────────────────────────────────────────────────────────
class CaseStatus(str, enum.Enum):
    """Processing status lifecycle for a video case.

    Transitions:
        UPLOADED → PROCESSING → ACTIVE_ANALYSIS → COMPLETED
        UPLOADED → PROCESSING → FAILED
        UPLOADED → PROCESSING → ACTIVE_ANALYSIS → FAILED
    """
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    ACTIVE_ANALYSIS = "ACTIVE_ANALYSIS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class RiskLevel(str, enum.Enum):
    """Risk evaluation levels for incidents and timeline entries.

    Values:
        LOW: No immediate threat or minor concern
        MEDIUM: Potential threat requiring attention
        HIGH: Active threat or critical incident
    """
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class LedgerEventType(str, enum.Enum):
    """Types of events recorded in the tamper-evident ledger.

    Each event type represents a specific state transition or action
    in the video analysis pipeline, forming a complete audit trail.
    """
    FILE_UPLOADED = "FILE_UPLOADED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    GEMINI_UPLOAD_COMPLETE = "GEMINI_UPLOAD_COMPLETE"
    INCIDENT_REPORT_GENERATED = "INCIDENT_REPORT_GENERATED"
    GEMINI_FILE_DELETED = "GEMINI_FILE_DELETED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"


# ── VideoCase Model ──────────────────────────────────────────────────────────
class VideoCase(Base):
    """Represents an uploaded video case and its analysis state.

    Each VideoCase tracks the full lifecycle of a video from upload through
    AI analysis to completion, including the cryptographic chain-of-custody hash.

    Attributes:
        id: UUID primary key, auto-generated by PostgreSQL.
        filename: Original filename of the uploaded video.
        original_md5: MD5 checksum computed from the uploaded file before processing.
        duration_seconds: Video duration in seconds (set after ffprobe analysis).
        file_size_bytes: Size of the uploaded file in bytes.
        status: Current processing state (see CaseStatus enum).
        risk_evaluation: Overall risk assessment (set after analysis completion).
        summary: AI-generated executive summary of the video content.
        final_ledger_hash: SHA-256 hash of the most recent ledger entry for this case.
        gemini_file_uri: Google Gemini file reference (cleared after deletion).
        celery_task_id: Celery task ID for status polling cross-reference.
        created_at: Timestamp when the case was created.
        updated_at: Timestamp of the last update to the case.
        timeline_entries: Related ChronologicalLog entries (cascade delete).
        ledger_entries: Related LedgerEntry audit records.
    """

    __tablename__ = "video_cases"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        doc="Unique case identifier (UUID v4)",
    )
    filename: Mapped[str] = mapped_column(
        Text, nullable=False, doc="Original uploaded filename"
    )
    original_md5: Mapped[str] = mapped_column(
        String(32), nullable=False, doc="MD5 checksum of the uploaded file"
    )
    duration_seconds: Mapped[Optional[float]] = mapped_column(
        Float, nullable=True, doc="Video duration in seconds (from ffprobe)"
    )
    file_size_bytes: Mapped[int] = mapped_column(
        BigInteger, nullable=False, doc="File size in bytes"
    )
    status: Mapped[CaseStatus] = mapped_column(
        Enum(CaseStatus, name="case_status", create_constraint=True),
        nullable=False,
        default=CaseStatus.UPLOADED,
        index=True,
        doc="Current processing status",
    )
    risk_evaluation: Mapped[Optional[RiskLevel]] = mapped_column(
        Enum(RiskLevel, name="risk_level", create_constraint=True),
        nullable=True,
        doc="Overall risk assessment (set after completion)",
    )
    summary: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True, doc="AI-generated executive summary"
    )
    crime_summary: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True, doc="Summary of the crime if it happened"
    )
    final_ledger_hash: Mapped[Optional[str]] = mapped_column(
        String(64),
        nullable=True,
        doc="SHA-256 hash of the latest ledger entry for this case",
    )
    gemini_file_uri: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Gemini file reference URI (cleared after deletion)",
    )
    celery_task_id: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        doc="Celery task ID for status cross-reference",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
        doc="Case creation timestamp",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
        onupdate=lambda: datetime.now(timezone.utc),
        doc="Last update timestamp",
    )

    # ── Relationships ────────────────────────────────────────────────────
    timeline_entries: Mapped[List["ChronologicalLog"]] = relationship(
        "ChronologicalLog",
        back_populates="video_case",
        cascade="all, delete-orphan",
        order_by="ChronologicalLog.sequence_order",
        doc="Ordered timeline entries from AI analysis",
    )
    ledger_entries: Mapped[List["LedgerEntry"]] = relationship(
        "LedgerEntry",
        back_populates="video_case",
        cascade="all, delete-orphan",
        order_by="LedgerEntry.id",
        doc="Tamper-evident audit log entries",
    )

    def __repr__(self) -> str:
        return (
            f"<VideoCase(id={self.id}, filename='{self.filename}', "
            f"status={self.status})>"
        )


# ── ChronologicalLog Model ──────────────────────────────────────────────────
class ChronologicalLog(Base):
    """Individual timeline entry from AI video analysis.

    Each entry represents a specific moment in the video with a description
    of what was detected, associated entities, and a risk assessment.
    Entries are ordered by sequence_order for deterministic rendering.

    Attributes:
        id: Auto-incrementing primary key.
        case_id: Foreign key to the parent VideoCase.
        timestamp_in_video: Display timestamp in MM:SS format.
        timestamp_seconds: Numeric seconds for video seeking.
        description: AI-generated description of the incident at this timestamp.
        entities_detected: Array of detected entities (vehicles, persons, etc).
        risk_level: Risk assessment for this specific timeline entry.
        sequence_order: Explicit ordering integer for strict chronological display.
        created_at: Timestamp when this entry was created.
        video_case: Back-reference to the parent VideoCase.
    """

    __tablename__ = "chronological_logs"

    id: Mapped[int] = mapped_column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
        doc="Auto-incrementing entry ID",
    )
    case_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("video_cases.id", ondelete="CASCADE"),
        nullable=False,
        doc="Parent video case UUID",
    )
    timestamp_in_video: Mapped[str] = mapped_column(
        Text, nullable=False, doc="Display timestamp (MM:SS format)"
    )
    timestamp_seconds: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        doc="Numeric seconds for video seeking in the frontend",
    )
    description: Mapped[str] = mapped_column(
        Text, nullable=False, doc="Description of the incident at this timestamp"
    )
    entities_detected: Mapped[Optional[List[str]]] = mapped_column(
        ARRAY(Text),
        nullable=True,
        doc="Array of detected entities (vehicles, weapons, persons, etc.)",
    )
    risk_level: Mapped[RiskLevel] = mapped_column(
        Enum(RiskLevel, name="risk_level", create_constraint=True, create_type=False),
        nullable=False,
        doc="Risk assessment for this timeline entry",
    )
    sequence_order: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        doc="Explicit ordering for strict chronological rendering",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
        doc="Entry creation timestamp",
    )

    # ── Relationships ────────────────────────────────────────────────────
    video_case: Mapped["VideoCase"] = relationship(
        "VideoCase",
        back_populates="timeline_entries",
    )

    # ── Composite Index ──────────────────────────────────────────────────
    __table_args__ = (
        Index(
            "ix_chronological_logs_case_sequence",
            "case_id",
            "sequence_order",
            unique=True,
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<ChronologicalLog(id={self.id}, case_id={self.case_id}, "
            f"timestamp={self.timestamp_in_video}, order={self.sequence_order})>"
        )


# ── LedgerEntry Model ────────────────────────────────────────────────────────
class LedgerEntry(Base):
    """Tamper-evident hash-chained audit log entry.

    Each entry contains a cryptographic hash linking it to the previous entry
    in the chain, forming an append-only audit trail. The database enforces
    immutability via triggers blocking UPDATE and DELETE operations.

    The chain starts with a genesis hash of 64 zeros for the first entry
    of each case.

    Attributes:
        id: Auto-incrementing primary key (also determines chain order).
        case_id: Foreign key to the parent VideoCase.
        event_type: Type of audit event (see LedgerEventType enum).
        payload_hash: SHA-256 hash of the canonicalized event payload.
        prev_hash: Hash of the previous entry in the chain (64 zeros for genesis).
        signature: HMAC signature of the payload_hash using LEDGER_SIGNING_KEY.
        payload_snapshot: Full event payload stored as JSONB for auditing.
        created_at: Timestamp when this entry was created.
        video_case: Back-reference to the parent VideoCase.
    """

    __tablename__ = "ledger_entries"

    id: Mapped[int] = mapped_column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
        doc="Auto-incrementing ledger entry ID (chain order)",
    )
    case_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("video_cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Parent video case UUID",
    )
    event_type: Mapped[LedgerEventType] = mapped_column(
        Enum(LedgerEventType, name="ledger_event_type", create_constraint=True),
        nullable=False,
        doc="Type of audit event",
    )
    payload_hash: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        doc="SHA-256 hash of the canonicalized payload",
    )
    prev_hash: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        doc="Hash of the previous entry (64 zeros for genesis)",
    )
    signature: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc="HMAC signature of the payload_hash",
    )
    payload_snapshot: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        doc="Full event payload for audit inspection",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
        doc="Entry creation timestamp",
    )

    # ── Relationships ────────────────────────────────────────────────────
    video_case: Mapped["VideoCase"] = relationship(
        "VideoCase",
        back_populates="ledger_entries",
    )

    def __repr__(self) -> str:
        return (
            f"<LedgerEntry(id={self.id}, case_id={self.case_id}, "
            f"event_type={self.event_type})>"
        )
